#!/usr/bin/env bash
# A bash script that displays "To infinity and beyond indefinitely"

i=0
while [ $i -le 1 ]
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo I am invincible!!!" SIGTERM
done
