#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 100

i=1

while [ $i -le 100 ]
do
	fifteen=$((i%15))
	five=$((i%5))
	three=$((i%3))

	if [ $fifteen -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $five -eq 0 ]
	then
		echo "Buzz"
	elif [ $three -eq 0 ]
	then
		echo "Fizz"
	else
		echo $i
	fi
	(( i++ ))
done
